# Generated by Django 4.0.6 on 2022-07-19 06:27

from django.db import migrations, models
import django.db.models.deletion
import unicodedata


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='category##', max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': (unicodedata.name,),
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='tag##', max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': (unicodedata.name,),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='product##', max_length=255)),
                ('description', models.TextField()),
                ('actualPrice', models.FloatField(default=0)),
                ('discountedPrice', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('countryOfOrigin', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productCategories', to='store.category')),
                ('prodImages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImage', to='store.images')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productTags', to='store.tag')),
            ],
        ),
    ]
