# Generated by Django 4.0.6 on 2022-07-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='product',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
