# Generated by Django 4.0.6 on 2022-07-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_slug_alter_images_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='productCategories', to='store.category'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodImages',
        ),
        migrations.AddField(
            model_name='product',
            name='prodImages',
            field=models.ManyToManyField(related_name='productImage', to='store.images'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='productTags', to='store.tag'),
        ),
    ]
