# Generated by Django 4.0.6 on 2022-07-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_categories_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodImages',
            field=models.ManyToManyField(blank=True, null=True, related_name='productImage', to='store.images'),
        ),
    ]
